"""Generate predict_<arch>.sh from a state_dict + a weights dir of .bin files."""
from pathlib import Path

from .archs.resnet import _num_blocks, _is_bottleneck


PREAMBLE = r"""#!/usr/bin/env bash
# Auto-generated by gdal-unet-export. Runs full {ARCH} U-Net inference using
# only gdal-conv2d subprocesses + base shell.
#
# Usage: predict_{ARCH}.sh <weights_dir> <input.tif> <output_probs.tif>
#
# Requires `gdal-conv2d` on PATH (or set GDAL_CONV2D env var).
set -euo pipefail

W="${{1:?weights dir}}"
IN="${{2:?input tif}}"
OUT="${{3:?output tif}}"

BIN="${{GDAL_CONV2D:-gdal-conv2d}}"
TH="${{GDAL_CONV2D_THREADS:-16}}"
WORK="${{WORK:-$(mktemp -d)}}"
mkdir -p "$WORK"
echo "[predict_{ARCH}] work=$WORK"

# Helper: read kernel shape from $W/shapes.txt
shape() {{
  grep "^$1 " "$W/shapes.txt" | awk '{{print $2}}'
}}

CO=(--co BIGTIFF=IF_SAFER --co INTERLEAVE=BAND)
CONV() {{
  # CONV <key> <in> <out> <stride> <padding> <activation>
  local key="$1" in="$2" out="$3" stride="$4" padding="$5" act="$6"
  local args=(--mode conv --in "$in"
              --kernel "$W/${{key}}.kernel.bin"
              --kernel-shape "$(shape "$key")"
              --stride "$stride" --padding "$padding"
              --activation "$act"
              --threads "$TH" "${{CO[@]}}" --out "$out")
  if [[ -f "$W/${{key}}.bn_a.bin" ]]; then
    args+=(--bn-a "$W/${{key}}.bn_a.bin" --bn-b "$W/${{key}}.bn_b.bin")
  elif [[ -f "$W/${{key}}.bias.bin" ]]; then
    args+=(--bias "$W/${{key}}.bias.bin")
  fi
  "$BIN" "${{args[@]}}"
}}

ADD() {{ "$BIN" --mode add "${{@}}" --threads "$TH" "${{CO[@]}}"; }}
CONCAT() {{ "$BIN" --mode concat "${{@}}" --threads "$TH" "${{CO[@]}}"; }}
UPSAMPLE() {{ "$BIN" --mode upsample --in "$1" --scale "$2" --method nearest --out "$3" --threads "$TH" "${{CO[@]}}"; }}
SCALE() {{ "$BIN" --mode scale --in "$1" --scale "$2" --out "$3" --threads "$TH" "${{CO[@]}}"; }}
MAXPOOL() {{ "$BIN" --mode maxpool --in "$1" --kernel-size "$2" --stride "$3" --padding "$4" --out "$5" --threads "$TH" "${{CO[@]}}"; }}
SOFTMAX() {{ "$BIN" --mode softmax --in "$1" --out "$2" --threads "$TH" "${{CO[@]}}"; }}

# ---- preprocess: x / 255 ----
SCALE "$IN" 0.00392156862745098 "$WORK/00_pre.tif"

# ---- stem: 7x7 stride 2 pad 3 + bn + relu ----
CONV stem  "$WORK/00_pre.tif" "$WORK/01_stem.tif"  2 3 relu

# ---- maxpool 3x3 stride 2 pad 1 ----
MAXPOOL "$WORK/01_stem.tif" 3 2 1 "$WORK/02_mp.tif"
"""


def _basic_block_sh(L: int, b: int, stride: int, has_ds: bool, in_var: str, out_var: str) -> str:
    pk = f"l{L}b{b}"
    s = f"""
# ---- basic block layer{L} block{b} (stride={stride}) ----
CONV {pk}_c1 "{in_var}" "$WORK/{pk}_c1.tif" {stride} 1 relu
CONV {pk}_c2 "$WORK/{pk}_c1.tif" "$WORK/{pk}_c2.tif" 1 1 none
"""
    if has_ds:
        s += f'CONV {pk}_ds "{in_var}" "$WORK/{pk}_ds.tif" {stride} 0 none\n'
        s += f'ADD --in "$WORK/{pk}_c2.tif" --in "$WORK/{pk}_ds.tif" --activation relu --out "{out_var}"\n'
    else:
        s += f'ADD --in "$WORK/{pk}_c2.tif" --in "{in_var}" --activation relu --out "{out_var}"\n'
    return s


def _bottleneck_block_sh(L: int, b: int, stride: int, has_ds: bool, in_var: str, out_var: str) -> str:
    pk = f"l{L}b{b}"
    # torchvision v1.5: stride lives on the 3x3 (conv2), 1x1s stay stride 1, pad 0.
    s = f"""
# ---- bottleneck block layer{L} block{b} (stride={stride}) ----
CONV {pk}_c1 "{in_var}" "$WORK/{pk}_c1.tif" 1 0 relu
CONV {pk}_c2 "$WORK/{pk}_c1.tif" "$WORK/{pk}_c2.tif" {stride} 1 relu
CONV {pk}_c3 "$WORK/{pk}_c2.tif" "$WORK/{pk}_c3.tif" 1 0 none
"""
    if has_ds:
        s += f'CONV {pk}_ds "{in_var}" "$WORK/{pk}_ds.tif" {stride} 0 none\n'
        s += f'ADD --in "$WORK/{pk}_c3.tif" --in "$WORK/{pk}_ds.tif" --activation relu --out "{out_var}"\n'
    else:
        s += f'ADD --in "$WORK/{pk}_c3.tif" --in "{in_var}" --activation relu --out "{out_var}"\n'
    return s


def emit_resnet(out: Path, *, arch: str, sd: dict):
    bottleneck = _is_bottleneck(sd)
    nb = _num_blocks(sd)
    blk_sh = _bottleneck_block_sh if bottleneck else _basic_block_sh

    parts: list[str] = [PREAMBLE.format(ARCH=arch)]

    # ---- Encoder layers ----
    # layer1: stride 1 throughout; in = $WORK/02_mp.tif
    in_var = "$WORK/02_mp.tif"
    feat_files = ["$WORK/00_pre.tif", "$WORK/01_stem.tif"]  # input + stem; (no mp feat)

    for L in (1, 2, 3, 4):
        for b in range(nb[L]):
            stride = 2 if (L > 1 and b == 0) else 1
            pk = f"l{L}b{b}"
            has_ds = f"encoder.layer{L}.{b}.downsample.0.weight" in sd
            out_var = f"$WORK/{pk}.tif"
            parts.append(blk_sh(L, b, stride, has_ds, in_var, out_var))
            in_var = out_var
        # after last block of stage L, record feature
        feat_files.append(in_var)

    # Decoder: smp.Unet reverses encoder features, uses the deepest as input
    # and the rest as skips.  --scale 2 upsample assumes input H,W are multiples
    # of 32 (else the per-block upsample target would need explicit dimensions).
    rev = list(reversed(feat_files[1:]))  # [l4, l3, l2, l1, stem]
    x = rev[0]
    skips = rev[1:] + [None]
    n_dec = int((out / "n_decoder_blocks.txt").read_text().strip())
    cur = x
    for i in range(n_dec):
        up = f"$WORK/dec_{i}_up.tif"
        parts.append(f'\n# ---- decoder block {i} ----\n')
        parts.append(f'UPSAMPLE "{cur}" 2 "{up}"\n')
        if skips[i] is not None:
            cat = f"$WORK/dec_{i}_cat.tif"
            parts.append(f'CONCAT --in "{up}" --in "{skips[i]}" --out "{cat}"\n')
            blk_in = cat
        else:
            blk_in = up
        c1 = f"$WORK/dec_{i}_c1.tif"
        c2 = f"$WORK/dec_{i}.tif"
        parts.append(f'CONV dec{i}_c1 "{blk_in}" "{c1}" 1 1 relu\n')
        parts.append(f'CONV dec{i}_c2 "{c1}" "{c2}" 1 1 relu\n')
        cur = c2

    parts.append('\n# ---- segmentation head + softmax ----\n')
    parts.append(f'CONV head "{cur}" "$WORK/logits.tif" 1 1 none\n')
    parts.append('SOFTMAX "$WORK/logits.tif" "$OUT"\n')
    parts.append('\necho "[predict_{}] wrote $OUT"\n'.format(arch))

    sh_path = out / f"predict_{arch}.sh"
    sh_path.write_text("".join(parts))
    sh_path.chmod(0o755)
